name: colorization
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.3
  - streamlit=1.34.0
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - pillow  
  - cudatoolkit=12.1
  - scikit-image
  - tqdm
  - scienceplots
  - pip
  - pip:
      - torch==2.2.2
      - torchvision
      - torchaudio
      - utils