name: colorization
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - anaconda::pandas
  - conda-forge::matplotlib
  - anaconda::scipy
  - anaconda::scikit-learn
  - prompt-toolkit
  - pure_eval
  - jedi
  - wcwidth
  - bzip2
  - nest-asyncio
  - vs2015_runtime
  - executing
  - vc
  - decorator
  - traitlets
  - libffi
  - zipp
  - packaging
  - zeromq
  - six
  - vc14_runtime
  - colorama
  - stack_data
  - exceptiongroup
  - ipython
  - wheel
  - typing_extensions
  - comm
  - psutil
  - python-dateutil
  - xz
  - asttokens
  - ucrt
  - setuptools
  - ca-certificates
  - platformdirs
  - pickleshare
  - importlib-metadata
  - python_abi
  - importlib_metadata
  - tzdata
  - pygments
  - libsqlite
  - pywin32
  - jupyter_client
  - tk
  - jupyter_core
  - pyzmq
  - matplotlib-inline
  - openssl
  - libsodium
  - tornado
  - debugpy
  - parso
  - libzlib
  - libexpat
  - pip
  - ipykernel
  - torchaudio
  - pytorch-cuda=12.1
  - pytorch
  - torchvision
  - scikit-image
  - conda-forge::tqdm
  - conda-forge::scienceplots